[2024-12-02T08:23:06.607+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T08:23:06.634+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.extract manual__2024-12-02T08:23:03.329268+00:00 [queued]>
[2024-12-02T08:23:06.651+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.extract manual__2024-12-02T08:23:03.329268+00:00 [queued]>
[2024-12-02T08:23:06.652+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-02T08:23:06.677+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-12-02 08:23:03.329268+00:00
[2024-12-02T08:23:06.694+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'extract', 'manual__2024-12-02T08:23:03.329268+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgaa2_xj5']
[2024-12-02T08:23:06.696+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11051) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T08:23:06.697+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask extract
[2024-12-02T08:23:06.698+0000] {standard_task_runner.py:72} INFO - Started process 11103 to run task
[2024-12-02T08:23:06.780+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.extract manual__2024-12-02T08:23:03.329268+00:00 [running]> on host a34e3ee3c8c3
[2024-12-02T08:23:06.955+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:23:03.329268+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:23:03.329268+00:00'
[2024-12-02T08:23:06.958+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T08:23:06.959+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T08:23:06.960+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-12-02 08:23:06.635825+00:00
[2024-12-02T08:23:06.961+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-02T08:23:06.962+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T08:23:07.065+0000] {logging_mixin.py:190} INFO - An error Occured during getting data from apiHTTPSConnectionPool(host='api.apify.com', port=443): Max retries exceeded with url: /v2/datasets/6v7wMjCoJEvcg4hZ2/items?token=apify_api_cVz6ZO0XzuFK70IYRkB66jMJAqMjFF1SppIy (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f58aac78890>: Failed to resolve 'api.apify.com' ([Errno -5] No address associated with hostname)"))
[2024-12-02T08:23:07.081+0000] {logging_mixin.py:190} INFO - Saving to staging area failed "None of [Index(['id', 'titleType', 'titleText', 'certificate', 'releaseDate', 'runtime',\n       'genres', 'directors', 'ratingsSummary', 'productionBudget',\n       'worldwideGross'],\n      dtype='object')] are in the [columns]"
[2024-12-02T08:23:07.082+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-02T08:23:07.096+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T08:23:07.097+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=IMDB_testing_DAG, task_id=extract, run_id=manual__2024-12-02T08:23:03.329268+00:00, execution_date=20241202T082303, start_date=20241202T082306, end_date=20241202T082307
[2024-12-02T08:23:07.120+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-02T08:23:07.122+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-02T08:23:07.123+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG queued_at:2024-12-02 08:23:03.407740+00:00
[2024-12-02T08:23:07.124+0000] {logging_mixin.py:190} INFO - Task hostname:a34e3ee3c8c3 operator:PythonOperator
[2024-12-02T08:23:07.164+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-02T08:23:07.203+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-02T08:23:07.207+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
